server:
  publicAddress: http://localhost:8089/loan-api
  servlet:
    context-path: /loan-api
  port: 8089
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: loanapi
    username: loanapi
    url: jdbc:postgresql://localhost:54325/loanapi
  sql:
    init:
      mode: always
      data-locations:
        - classpath:/database/user_info/users.sql
  liquibase:
    change-log: database/db_changelog.xml
    password: loanapi
    user: loanapi

amount:
  min: 10000
  max: 1000000000
