version: '3.9'
services:
  db:
    container_name: loanapi-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "54325:5432"
    environment:
      POSTGRES_DB: loanapi
      POSTGRES_USER: loanapi
      POSTGRES_PASSWORD: loanapi